### ISSUE TITLE
No environment variable for strict-ssl

### ISSUE THREAD

**Issue by rcollette** [bower/config#19]
As far as I can tell, there is no ability to set the strict-ssl setting to false using an environment variable (I'm on Windows).  I am using bower behind a proxy which inserts its own certificates in between.   Until I can resolve with my networking group (which can take a while), I have been able to get bower to work the command line setting --config.strict-ssl=false but trying strict-ssl=false or STRICT-SSL=false as an environment variable does not work and looking at the default settings code I don't see any usage of an environment variable for strict-ssl.

**Comment by sheerun** [comment]
You can use `bower_strict_ssl` environment variable. StrictSsl is used in UrlResolver in bower.

Sorry for late response, I'm triaging issues on this repository.
