### ISSUE TITLE
Add auto-sort (bool) option to .bowerrc

### ISSUE THREAD

**Issue by leocaseiro** [bower/config#29]
Some projects read the bower.json file to include their JavaScript and CSS libraries in their minified JavaScript, or sometimes, to inject in their HTML.

Libraries like [BowerMain](https://github.com/frodefi/bower-main), [Wiredep](https://github.com/taptapship/wiredep) combined with Gulp/Grunt can be very handle for generate minified javascript files or, to inject into html.

Bower recently has added an [Auto-Sort process](https://github.com/bower/bower/pull/1381) that runs after each --save or --save-dev, That can be organized for some projects.
However, when uses JavaScripts extensions that needs dependency injection like AngularJS + jQuery, Bootstrap + jQuery, sometimes jQuery plugins that need to be added after jQuery only,  could not be added and concatenated in a wrong order.  

Also, in my case, I have a project with a big team that very often add bower libraries, after the automatically "autosorter", the number of conflicts has been increased on the bower.json.

I'd like to suggest an option called autosort which could be optional for each project.

    .bowerrc
    {
        "autosort": false
    }

There's an [issue on Bower Library](https://github.com/bower/bower/issues/1897), but I believe the option needs to be included in bower-config before we add the condition for the Bower/Project.js.

**Comment by sheerun** [comment]
I agree we need to put it behind a flag for now..

**Comment by leocaseiro** [comment]
May I send a pull request with a default value as false, or should it be true?

**Comment by sheerun** [comment]
I think it should be false. I'm also thinking about `--beta` flag for bower for enabling features that will go as defaults to Bower 2.0..

**Comment by bobmulder** [comment]
Just a suggestion. I don't think this option should be located in .bowrrc. The bower.json file would better for shared projects, isn't it?

**Comment by leocaseiro** [comment]
How about not shared projects?

**Comment by bobmulder** [comment]
Makes no difference for not shared projects, or am I wrong? Look, when you share a project the .bowerrc isn't shared. For private projects this is no issue...

**Comment by leocaseiro** [comment]
Actually the examples I mentioned are manly private projects. These are the projects which use Gulp/Grunt with third-party libraries as AngularJS, jQuery, Plugins and so on...the same projects that need to load JavaScripts in correctly order.

I understand that bower settings like directory, colors and more optional settings are located in .bowerrc, why this option should be in bower.json which is most used for shared libraries?

**Comment by bobmulder** [comment]
Thanks for your feedback. For example: I use bower and via wiredep (gulp) I load all dependencies automatically. I can use this for my own but want the sort for my mates too. .bowerrc is ignored and bower.json is shared. So in that case to prevent (still) errors on sharing projects and forks, the option should be located there ;)

**Comment by leocaseiro** [comment]
I see, I've never left my .bowerrc as ignored, because normally I set the *{directory:lib}* there. Either **.bowerrc** or **bower.json**, this should be mentioned on the project documentation, though.

**Comment by bobmulder** [comment]
In that case I am wrong and .bowerrc is right! :+1:

**Comment by michgeek** [comment]
Stop it @bobmulder You already broke lots of automated build with that idea. Don't spread it anymore. Dependency sorting is useless. Sorry to say.

**Comment by michgeek** [comment]
Removed previous comment. Sorry for the confusion.

**Comment by sheerun** [comment]
I'll revert this feature asap and put behind a flag. Sorry for that. We'll
introduce --beta flag for explicitly opting-in in for such features.
>
>

**Comment by bobmulder** [comment]
@michgeek Why did you add that comment? Please explain.

@sheerun Thanks for your attention. Good to see you are listening to the users ;) Keep up te good work!

**Comment by michgeek** [comment]
@bobmulder I was reading at several discussion at the time and I got confused. I though you were the author of that idea about auto-sorting the dependencies order alphabetically. Please accept my apologies for the confusion. Let's have a :coffee: :)

**Comment by bobmulder** [comment]
We should drink a :beers: together ;) It's okay @michgeek ;) If you want to discuss or chat, I'm available at https://gitter.im/bobmulder ;)

**Comment by sheerun** [comment]
Now this feature is reverted completely. If we introduce this feature again, It'll be behind a flag.
