### ISSUE TITLE
Error tmpDir on bower install

### ISSUE THREAD

**Issue by antonybudianto** [bower/config#35]
Hi, I'm trying to do `bower install` in Openshift and got this error:
```bash
root/data/n/versions/node/0.12.0/lib/node_modules/bower/node_modules/bower-config/lib/util/paths.js:21
var tmp = path.join(os.tmpdir ? os.tmpdir() : os.tmpDir(), user);
                                                 ^
TypeError: Object #<Object> has no method 'tmpDir'
 ```

My node npm version
```bash
+ /var/lib/openshift/56xxxx167xxx8exe7f00009d/app-root/data/n/versions/node/0.12.0/bin/node -v
v0.12.0
+ /var/lib/openshift/5xxxxx167xx8e1fe7f00009d/app-root/data/n/versions/node/0.12.0/bin/npm -v
2.5.1
```

Maybe related to [this](https://github.com/felixge/node-formidable/issues/230)
`os.tmpDir()` not exists in [here](https://github.com/bower/config/blob/master/lib/util/paths.js#L21)

Thank you

**Comment by paulohp** [comment]
Hey @antonybudianto I'm trying to reproduce the error here. Which version of bower you're using?

Thanks!

**Comment by antonybudianto** [comment]
latest version of bower, thanks

**Comment by antonybudianto** [comment]
FYI of course it works in my machines (OSX and windows), I suspect it's operating system issue

**Comment by smali-kazmi** [comment]
@antonybudianto yes its true it is operating system issue; trying to install openshift; on my machine to reproduce and fix this issue properly

**Comment by antonybudianto7** [comment]
thank you for the work man! @smali-kazmi :+1:

**Comment by antonybudianto** [comment]
thank you for the work man! @smali-kazmi :+1:

**Comment by sheerun** [comment]
What `console.log(os.tmpdir)` returns for you? @antonybudianto

**Comment by antonybudianto** [comment]
undefined

**Comment by sheerun** [comment]
Then what is the proper way of getting temp dir on your platform?

**Comment by antonybudianto** [comment]
i don't know other than using os.tmpdir, maybe the bower detect the old node version (openshift catridge has default node which is old, 0.6.x)

**Comment by sheerun** [comment]
Node 0.6 doesn't support tmpdir at all: https://nodejs.org/docs/v0.6.0/api/os.html

Bower supports only node >= 0.10

**Comment by antonybudianto** [comment]
that's why I aliased the node to my own installed node (0.12.0), but seems like bower still look the 0.6.x node

**Comment by sheerun** [comment]
It seems like so :) I'm not sure how to help. You probably need to use something like nvm.

**Comment by antonybudianto** [comment]
I don't have sudo permission in there, not even permission to install
Thanks for your help though

**Comment by sheerun** [comment]
You don't need sudo to install nvm.

**Comment by antonybudianto** [comment]
Okay I will try
