### ISSUE TITLE
Regression not allowing the use of inline bash within script hooks

### ISSUE THREAD

**Issue by oxyc** [bower/config#47]
https://github.com/bower/config/commit/31451daa7daa5d934a3b8231f57070d7caa3654a introduced the support for environment variables in the bowerrc. This now breaks my postinstall hook which creates `.scss` files from all `.css` files.

Error: Environment variable used in .bowerrc is not defined: ${n:0:-4}

```json
{
  "directory": "bower_components",
  "scripts": {
    "postinstall": "find bower_components/ -type f -name '*.css' -exec bash -c 'n=\"{}\"; cp -v \"$n\" \"${n:0:-4}.scss\"' \\;"
  }
}
```

I'm aware that I can just move this to a separate script file, but I'd still prefer having it contained in `.bowerrc`. Thoughts?

**Comment by sheerun** [comment]
@mithun Could you look at it and fix it somehow maybe?

@oxyc Would ability to escape `$` somehow be enough?

**Comment by mithun** [comment]
@sheerun I wasn't awake of [hooks](https://github.com/bower/bower/blob/master/HOOKS.md). Shouldn't that be part of the [spec](https://github.com/bower/spec/blob/master/config.md)?

Given that the _scripts_ are already executing in the shell, I'm inclined to skip the environment variable evaluation for that node.

Thoughts?

**Comment by oxyc** [comment]
@sheerun escaping would be enough yes but @mithun solution would be great–You wouldn't really expect it was necessary to escape `$` in this context.

**Comment by sheerun** [comment]
Yes, let's disable escaping for all hooks. @mithun Could you prepare a PR?

**Comment by mithun** [comment]
@sheerun opened #48

**Comment by oxyc** [comment]
Any chance of a new release soon? this is still broken across all our projects

**Comment by sheerun** [comment]
It was released long time ago

**Comment by oxyc** [comment]
https://github.com/bower/config/compare/1.3.0...master

Not on GitHub at least.
