### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by oxyc** [bower/config#50]
Latest release was `1.3.0` which is missing the fix for #47. Diff: https://github.com/bower/config/compare/1.3.0...master 

NPM is also on `1.3.0` https://www.npmjs.com/package/bower-config

**Comment by oxyc** [comment]
... still not released. I will now consider this an abandoned project.

**Comment by sheerun** [comment]
1.3.1 has been released at 1 Apr and is now also tagged
