### ISSUE TITLE
Add DEFAULT_REGISTRY

### ISSUE THREAD

**Issue by satazor** [bower/config#6]
Add a DEFAULT_REGISTRY key to the `Config` class that exposes the bower registry URL (heroku) that basically is an alias to  https://github.com/bower/config/blob/master/lib/util/defaults.js#L25

Also, this would be available in the .bowerrc, file.. something like: {{default-registry}}

This is a follow up of https://github.com/bower/bower/issues/745.

**Comment by sheerun** [comment]
Thanks to Pluggable Resolvers, this constant is not needed now. Besides bower's default registry default url won't change ever.

**Comment by sheerun** [comment]
Also, it seems already exposed :)
